{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "mount_file_id": "1fmt8RiulRca_lfO6mpOV6UYjkbA3BHX7",
      "authorship_tag": "ABX9TyNZDDor8zDKHLdbgRgiCgbM",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/AndresPlazas19931504/scrapper-deportes-devops/blob/main/Plazas__Andres_Analizando_EA1.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import requests\n",
        "from bs4 import BeautifulSoup\n",
        "import pandas as pd\n",
        "\n",
        "headers = {\n",
        "    \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36\"\n",
        "}"
      ],
      "metadata": {
        "id": "8tUorAOyl45Z"
      },
      "execution_count": 1,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def web_scraping_espn_combinado():\n",
        "    try:\n",
        "        url = \"https://www.espn.com.co/futbol/posiciones/_/liga/eng.1\"\n",
        "        response = requests.get(url, headers=headers)\n",
        "\n",
        "        response.raise_for_status()\n",
        "\n",
        "        soup = BeautifulSoup(response.content, \"html.parser\")\n",
        "\n",
        "        tabla_posiciones1 = soup.find(\"table\", {\"class\": \"Table Table--align-right Table--fixed Table--fixed-left\"})\n",
        "        filas1 = tabla_posiciones1.find_all(\"tr\", {\"class\": [\"Table__TR Table__TR--sm Table__even\", \"filled Table__TR Table__TR--sm Table__even\"]})\n",
        "        posiciones = []\n",
        "        abreviaturas = []\n",
        "        nombres = []\n",
        "        for fila in filas1:\n",
        "            posicion = fila.find(\"span\", {\"class\": \"team-position ml2 pr3\"}).text\n",
        "            nombre_equipo = fila.find(\"span\", {\"class\": \"hide-mobile\"}).text\n",
        "            abreviatura_equipo = fila.find(\"span\", {\"class\": \"dn show-mobile\"}).text\n",
        "            posiciones.append(posicion)\n",
        "            abreviaturas.append(abreviatura_equipo)\n",
        "            nombres.append(nombre_equipo)\n",
        "        df1 = pd.DataFrame({\"Posición\": posiciones, \"Avr\": abreviaturas, \"Nombre\": nombres})\n",
        "\n",
        "        tabla_posiciones2 = soup.find(\"table\", {\"class\": \"Table Table--align-right\"})\n",
        "        tbody = tabla_posiciones2.find(\"tbody\", {\"class\": \"Table__TBODY\"})\n",
        "        filas2 = tbody.find_all(\"tr\", {\"class\": [\"Table__TR Table__TR--sm Table__even\", \"filled Table__TR Table__TR--sm Table__even\"]})\n",
        "        datos_por_idx = {}\n",
        "        for fila in filas2:\n",
        "            data_idx = fila.get(\"data-idx\")\n",
        "            if data_idx is None:\n",
        "                continue\n",
        "            stat_cells = fila.find_all(\"span\", {\"class\": \"stat-cell\"})\n",
        "            if data_idx not in datos_por_idx:\n",
        "                datos_por_idx[data_idx] = []\n",
        "            datos_por_idx[data_idx].extend([cell.text for cell in stat_cells])\n",
        "        df2 = pd.DataFrame(datos_por_idx).T\n",
        "\n",
        "        df1 = df1.reset_index(drop=True)\n",
        "        df2 = df2.reset_index(drop=True)\n",
        "\n",
        "        df_final = pd.concat([df1, df2], axis=1)\n",
        "\n",
        "        nuevos_nombres_columnas = {\n",
        "            'Posición': 'Posicion',\n",
        "            'Avr': 'Abreviatura',\n",
        "            'Nombre': 'Equipo',\n",
        "            0: 'Número de partidos jugados',\n",
        "            1: 'El número de partidos ganados',\n",
        "            2: 'Empate',\n",
        "            3: 'Derrotas',\n",
        "            4: 'Goles a favor',\n",
        "            5: 'Goles en contra',\n",
        "            6: 'Diferencia de puntos',\n",
        "            7: 'Puntos'\n",
        "\n",
        "        }\n",
        "        df_final = df_final.rename(columns=nuevos_nombres_columnas)\n",
        "\n",
        "\n",
        "        return df_final\n",
        "\n",
        "    except requests.exceptions.RequestException as e:\n",
        "        print(f\"Error de conexión: {e}\")\n",
        "\n",
        "    except Exception as e:\n",
        "        print(f\"Error inesperado: {e}\")\n",
        "\n",
        "web_scraping_espn_combinado()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 676
        },
        "id": "Q3xT5aPjlh1X",
        "outputId": "c11546fb-f7d5-4f6a-b3be-7a9e9902cf20"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   Posicion Abreviatura                   Equipo Número de partidos jugados  \\\n",
              "0         1         LIV                Liverpool                         37   \n",
              "1         2         ARS                  Arsenal                         37   \n",
              "2         3         MCI          Manchester City                         37   \n",
              "3         4         NEW         Newcastle United                         37   \n",
              "4         5         CHE                  Chelsea                         37   \n",
              "5         6         AVL              Aston Villa                         37   \n",
              "6         7         FOR        Nottingham Forest                         37   \n",
              "7         8         BHA   Brighton & Hove Albion                         37   \n",
              "8         9         BRN                Brentford                         37   \n",
              "9        10         FUL                   Fulham                         37   \n",
              "10       11         BOU          AFC Bournemouth                         37   \n",
              "11       12         CRY           Crystal Palace                         37   \n",
              "12       13         EVE                  Everton                         37   \n",
              "13       14         WOL  Wolverhampton Wanderers                         37   \n",
              "14       15         WHU          West Ham United                         37   \n",
              "15       16         MUN        Manchester United                         37   \n",
              "16       17         TOT        Tottenham Hotspur                         37   \n",
              "17       18         LEI           Leicester City                         37   \n",
              "18       19         IPS             Ipswich Town                         37   \n",
              "19       20         SOU              Southampton                         37   \n",
              "\n",
              "   El número de partidos ganados Empate Derrotas Goles a favor  \\\n",
              "0                             25      8        4            85   \n",
              "1                             19     14        4            67   \n",
              "2                             20      8        9            70   \n",
              "3                             20      6       11            68   \n",
              "4                             19      9        9            63   \n",
              "5                             19      9        9            58   \n",
              "6                             19      8       10            58   \n",
              "7                             15     13        9            62   \n",
              "8                             16      7       14            65   \n",
              "9                             15      9       13            54   \n",
              "10                            14     11       12            56   \n",
              "11                            13     13       11            50   \n",
              "12                            10     15       12            41   \n",
              "13                            12      5       20            53   \n",
              "14                            10     10       17            43   \n",
              "15                            10      9       18            42   \n",
              "16                            11      5       21            63   \n",
              "17                             6      7       24            33   \n",
              "18                             4     10       23            35   \n",
              "19                             2      6       29            25   \n",
              "\n",
              "   Goles en contra Diferencia de puntos Puntos  \n",
              "0               40                  +45     83  \n",
              "1               33                  +34     71  \n",
              "2               44                  +26     68  \n",
              "3               46                  +22     66  \n",
              "4               43                  +20     66  \n",
              "5               49                   +9     66  \n",
              "6               45                  +13     65  \n",
              "7               58                   +4     58  \n",
              "8               56                   +9     55  \n",
              "9               52                   +2     54  \n",
              "10              46                  +10     53  \n",
              "11              50                    0     52  \n",
              "12              44                   -3     45  \n",
              "13              68                  -15     41  \n",
              "14              61                  -18     40  \n",
              "15              54                  -12     39  \n",
              "16              61                   +2     38  \n",
              "17              78                  -45     25  \n",
              "18              79                  -44     22  \n",
              "19              84                  -59     12  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-3c012eb9-69ee-4042-b983-3a016ae51f08\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Posicion</th>\n",
              "      <th>Abreviatura</th>\n",
              "      <th>Equipo</th>\n",
              "      <th>Número de partidos jugados</th>\n",
              "      <th>El número de partidos ganados</th>\n",
              "      <th>Empate</th>\n",
              "      <th>Derrotas</th>\n",
              "      <th>Goles a favor</th>\n",
              "      <th>Goles en contra</th>\n",
              "      <th>Diferencia de puntos</th>\n",
              "      <th>Puntos</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>LIV</td>\n",
              "      <td>Liverpool</td>\n",
              "      <td>37</td>\n",
              "      <td>25</td>\n",
              "      <td>8</td>\n",
              "      <td>4</td>\n",
              "      <td>85</td>\n",
              "      <td>40</td>\n",
              "      <td>+45</td>\n",
              "      <td>83</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>ARS</td>\n",
              "      <td>Arsenal</td>\n",
              "      <td>37</td>\n",
              "      <td>19</td>\n",
              "      <td>14</td>\n",
              "      <td>4</td>\n",
              "      <td>67</td>\n",
              "      <td>33</td>\n",
              "      <td>+34</td>\n",
              "      <td>71</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>MCI</td>\n",
              "      <td>Manchester City</td>\n",
              "      <td>37</td>\n",
              "      <td>20</td>\n",
              "      <td>8</td>\n",
              "      <td>9</td>\n",
              "      <td>70</td>\n",
              "      <td>44</td>\n",
              "      <td>+26</td>\n",
              "      <td>68</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>NEW</td>\n",
              "      <td>Newcastle United</td>\n",
              "      <td>37</td>\n",
              "      <td>20</td>\n",
              "      <td>6</td>\n",
              "      <td>11</td>\n",
              "      <td>68</td>\n",
              "      <td>46</td>\n",
              "      <td>+22</td>\n",
              "      <td>66</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>CHE</td>\n",
              "      <td>Chelsea</td>\n",
              "      <td>37</td>\n",
              "      <td>19</td>\n",
              "      <td>9</td>\n",
              "      <td>9</td>\n",
              "      <td>63</td>\n",
              "      <td>43</td>\n",
              "      <td>+20</td>\n",
              "      <td>66</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>6</td>\n",
              "      <td>AVL</td>\n",
              "      <td>Aston Villa</td>\n",
              "      <td>37</td>\n",
              "      <td>19</td>\n",
              "      <td>9</td>\n",
              "      <td>9</td>\n",
              "      <td>58</td>\n",
              "      <td>49</td>\n",
              "      <td>+9</td>\n",
              "      <td>66</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>7</td>\n",
              "      <td>FOR</td>\n",
              "      <td>Nottingham Forest</td>\n",
              "      <td>37</td>\n",
              "      <td>19</td>\n",
              "      <td>8</td>\n",
              "      <td>10</td>\n",
              "      <td>58</td>\n",
              "      <td>45</td>\n",
              "      <td>+13</td>\n",
              "      <td>65</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>8</td>\n",
              "      <td>BHA</td>\n",
              "      <td>Brighton &amp; Hove Albion</td>\n",
              "      <td>37</td>\n",
              "      <td>15</td>\n",
              "      <td>13</td>\n",
              "      <td>9</td>\n",
              "      <td>62</td>\n",
              "      <td>58</td>\n",
              "      <td>+4</td>\n",
              "      <td>58</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>9</td>\n",
              "      <td>BRN</td>\n",
              "      <td>Brentford</td>\n",
              "      <td>37</td>\n",
              "      <td>16</td>\n",
              "      <td>7</td>\n",
              "      <td>14</td>\n",
              "      <td>65</td>\n",
              "      <td>56</td>\n",
              "      <td>+9</td>\n",
              "      <td>55</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>10</td>\n",
              "      <td>FUL</td>\n",
              "      <td>Fulham</td>\n",
              "      <td>37</td>\n",
              "      <td>15</td>\n",
              "      <td>9</td>\n",
              "      <td>13</td>\n",
              "      <td>54</td>\n",
              "      <td>52</td>\n",
              "      <td>+2</td>\n",
              "      <td>54</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10</th>\n",
              "      <td>11</td>\n",
              "      <td>BOU</td>\n",
              "      <td>AFC Bournemouth</td>\n",
              "      <td>37</td>\n",
              "      <td>14</td>\n",
              "      <td>11</td>\n",
              "      <td>12</td>\n",
              "      <td>56</td>\n",
              "      <td>46</td>\n",
              "      <td>+10</td>\n",
              "      <td>53</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11</th>\n",
              "      <td>12</td>\n",
              "      <td>CRY</td>\n",
              "      <td>Crystal Palace</td>\n",
              "      <td>37</td>\n",
              "      <td>13</td>\n",
              "      <td>13</td>\n",
              "      <td>11</td>\n",
              "      <td>50</td>\n",
              "      <td>50</td>\n",
              "      <td>0</td>\n",
              "      <td>52</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>12</th>\n",
              "      <td>13</td>\n",
              "      <td>EVE</td>\n",
              "      <td>Everton</td>\n",
              "      <td>37</td>\n",
              "      <td>10</td>\n",
              "      <td>15</td>\n",
              "      <td>12</td>\n",
              "      <td>41</td>\n",
              "      <td>44</td>\n",
              "      <td>-3</td>\n",
              "      <td>45</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>13</th>\n",
              "      <td>14</td>\n",
              "      <td>WOL</td>\n",
              "      <td>Wolverhampton Wanderers</td>\n",
              "      <td>37</td>\n",
              "      <td>12</td>\n",
              "      <td>5</td>\n",
              "      <td>20</td>\n",
              "      <td>53</td>\n",
              "      <td>68</td>\n",
              "      <td>-15</td>\n",
              "      <td>41</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>14</th>\n",
              "      <td>15</td>\n",
              "      <td>WHU</td>\n",
              "      <td>West Ham United</td>\n",
              "      <td>37</td>\n",
              "      <td>10</td>\n",
              "      <td>10</td>\n",
              "      <td>17</td>\n",
              "      <td>43</td>\n",
              "      <td>61</td>\n",
              "      <td>-18</td>\n",
              "      <td>40</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>15</th>\n",
              "      <td>16</td>\n",
              "      <td>MUN</td>\n",
              "      <td>Manchester United</td>\n",
              "      <td>37</td>\n",
              "      <td>10</td>\n",
              "      <td>9</td>\n",
              "      <td>18</td>\n",
              "      <td>42</td>\n",
              "      <td>54</td>\n",
              "      <td>-12</td>\n",
              "      <td>39</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>16</th>\n",
              "      <td>17</td>\n",
              "      <td>TOT</td>\n",
              "      <td>Tottenham Hotspur</td>\n",
              "      <td>37</td>\n",
              "      <td>11</td>\n",
              "      <td>5</td>\n",
              "      <td>21</td>\n",
              "      <td>63</td>\n",
              "      <td>61</td>\n",
              "      <td>+2</td>\n",
              "      <td>38</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>17</th>\n",
              "      <td>18</td>\n",
              "      <td>LEI</td>\n",
              "      <td>Leicester City</td>\n",
              "      <td>37</td>\n",
              "      <td>6</td>\n",
              "      <td>7</td>\n",
              "      <td>24</td>\n",
              "      <td>33</td>\n",
              "      <td>78</td>\n",
              "      <td>-45</td>\n",
              "      <td>25</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>18</th>\n",
              "      <td>19</td>\n",
              "      <td>IPS</td>\n",
              "      <td>Ipswich Town</td>\n",
              "      <td>37</td>\n",
              "      <td>4</td>\n",
              "      <td>10</td>\n",
              "      <td>23</td>\n",
              "      <td>35</td>\n",
              "      <td>79</td>\n",
              "      <td>-44</td>\n",
              "      <td>22</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>19</th>\n",
              "      <td>20</td>\n",
              "      <td>SOU</td>\n",
              "      <td>Southampton</td>\n",
              "      <td>37</td>\n",
              "      <td>2</td>\n",
              "      <td>6</td>\n",
              "      <td>29</td>\n",
              "      <td>25</td>\n",
              "      <td>84</td>\n",
              "      <td>-59</td>\n",
              "      <td>12</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-3c012eb9-69ee-4042-b983-3a016ae51f08')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-3c012eb9-69ee-4042-b983-3a016ae51f08 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-3c012eb9-69ee-4042-b983-3a016ae51f08');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    <div id=\"df-c94404e4-b4d6-4256-857a-dfda6cd37edc\">\n",
              "      <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-c94404e4-b4d6-4256-857a-dfda6cd37edc')\"\n",
              "                title=\"Suggest charts\"\n",
              "                style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "      </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "      <script>\n",
              "        async function quickchart(key) {\n",
              "          const quickchartButtonEl =\n",
              "            document.querySelector('#' + key + ' button');\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "          try {\n",
              "            const charts = await google.colab.kernel.invokeFunction(\n",
              "                'suggestCharts', [key], {});\n",
              "          } catch (error) {\n",
              "            console.error('Error during call to suggestCharts:', error);\n",
              "          }\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "        }\n",
              "        (() => {\n",
              "          let quickchartButtonEl =\n",
              "            document.querySelector('#df-c94404e4-b4d6-4256-857a-dfda6cd37edc button');\n",
              "          quickchartButtonEl.style.display =\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "        })();\n",
              "      </script>\n",
              "    </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"web_scraping_espn_combinado()\",\n  \"rows\": 20,\n  \"fields\": [\n    {\n      \"column\": \"Posicion\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 20,\n        \"samples\": [\n          \"1\",\n          \"18\",\n          \"16\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Abreviatura\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 20,\n        \"samples\": [\n          \"LIV\",\n          \"LEI\",\n          \"MUN\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Equipo\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 20,\n        \"samples\": [\n          \"Liverpool\",\n          \"Leicester City\",\n          \"Manchester United\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"N\\u00famero de partidos jugados\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"37\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"El n\\u00famero de partidos ganados\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 13,\n        \"samples\": [\n          \"4\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Empate\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 10,\n        \"samples\": [\n          \"5\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Derrotas\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 14,\n        \"samples\": [\n          \"18\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Goles a favor\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 18,\n        \"samples\": [\n          \"85\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Goles en contra\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 17,\n        \"samples\": [\n          \"40\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Diferencia de puntos\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 18,\n        \"samples\": [\n          \"+45\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Puntos\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 18,\n        \"samples\": [\n          \"83\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 2
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "import sqlite3\n",
        "\n",
        "drive.mount('/content/drive')\n",
        "\n",
        "database_path = '/content/drive/MyDrive/Pad2025/Actividad_pad.db'\n",
        "\n",
        "try:\n",
        "    conn = sqlite3.connect(database_path)\n",
        "    cursor = conn.cursor()\n",
        "\n",
        "    cursor.execute(\"SELECT SQLITE_VERSION()\")\n",
        "    version = cursor.fetchone()[0]\n",
        "    print(f\"Versión de SQLite: {version}\")\n",
        "\n",
        "    conn.close()\n",
        "\n",
        "except sqlite3.Error as e:\n",
        "    print(f\"Error al conectar a SQLite: {e}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "iSwIAk4Vw_rU",
        "outputId": "20338257-2787-4f5b-9e77-6dc14757d597"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n",
            "Versión de SQLite: 3.37.2\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "try:\n",
        "    conn = sqlite3.connect(database_path)\n",
        "    cursor = conn.cursor()\n",
        "\n",
        "    cursor.execute('''\n",
        "        CREATE TABLE IF NOT EXISTS PremierLeague (\n",
        "            Posicion INTEGER,\n",
        "            Abreviatura TEXT,\n",
        "            Equipo TEXT,\n",
        "            \"Número de partidos jugados\" INTEGER,\n",
        "            \"El número de partidos ganados\" INTEGER,\n",
        "            Empate INTEGER,\n",
        "            Derrotas INTEGER,\n",
        "            \"Goles a favor\" INTEGER,\n",
        "            \"Goles en contra\" INTEGER,\n",
        "            \"Diferencia de puntos\" INTEGER,\n",
        "            Puntos INTEGER\n",
        "        )\n",
        "    ''')\n",
        "\n",
        "    conn.commit()\n",
        "    conn.close()\n",
        "\n",
        "    print(\"Tabla 'PremierLeague' creada exitosamente en la base de datos.\")\n",
        "\n",
        "except sqlite3.Error as e:\n",
        "    print(f\"Error al crear la tabla: {e}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "lwxlRPrU5G3B",
        "outputId": "170681a0-479a-4f93-8380-cb9936625a47"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Tabla 'PremierLeague' creada exitosamente en la base de datos.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "try:\n",
        "    conn = sqlite3.connect(database_path)\n",
        "\n",
        "    df_final = web_scraping_espn_combinado()\n",
        "    df_final.to_sql('PremierLeague', conn, if_exists='replace', index=False)\n",
        "\n",
        "    conn.close()\n",
        "\n",
        "    print(\"Datos insertados correctamente en la tabla 'PremierLeague'.\")\n",
        "\n",
        "except sqlite3.Error as e:\n",
        "    print(f\"Error al insertar los datos: {e}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "31_Qh8NW5nOk",
        "outputId": "0702e329-39a0-4f33-b7be-298624f89f25"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Datos insertados correctamente en la tabla 'PremierLeague'.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "try:\n",
        "    conn = sqlite3.connect(database_path)\n",
        "    cursor = conn.cursor()\n",
        "\n",
        "    cursor.execute(\"SELECT * FROM PremierLeague\")\n",
        "\n",
        "    results = cursor.fetchall()\n",
        "\n",
        "    for row in results:\n",
        "        print(row)\n",
        "\n",
        "    df = pd.DataFrame(results, columns=[description[0] for description in cursor.description])\n",
        "\n",
        "    conn.close()\n",
        "\n",
        "except sqlite3.Error as e:\n",
        "    print(f\"Error al consultar los datos: {e}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "lI6LMet55u43",
        "outputId": "516eb050-18e9-4952-899a-c8a535fddc63"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "('1', 'LIV', 'Liverpool', '37', '25', '8', '4', '85', '40', '+45', '83')\n",
            "('2', 'ARS', 'Arsenal', '37', '19', '14', '4', '67', '33', '+34', '71')\n",
            "('3', 'MCI', 'Manchester City', '37', '20', '8', '9', '70', '44', '+26', '68')\n",
            "('4', 'NEW', 'Newcastle United', '37', '20', '6', '11', '68', '46', '+22', '66')\n",
            "('5', 'CHE', 'Chelsea', '37', '19', '9', '9', '63', '43', '+20', '66')\n",
            "('6', 'AVL', 'Aston Villa', '37', '19', '9', '9', '58', '49', '+9', '66')\n",
            "('7', 'FOR', 'Nottingham Forest', '37', '19', '8', '10', '58', '45', '+13', '65')\n",
            "('8', 'BHA', 'Brighton & Hove Albion', '37', '15', '13', '9', '62', '58', '+4', '58')\n",
            "('9', 'BRN', 'Brentford', '37', '16', '7', '14', '65', '56', '+9', '55')\n",
            "('10', 'FUL', 'Fulham', '37', '15', '9', '13', '54', '52', '+2', '54')\n",
            "('11', 'BOU', 'AFC Bournemouth', '37', '14', '11', '12', '56', '46', '+10', '53')\n",
            "('12', 'CRY', 'Crystal Palace', '37', '13', '13', '11', '50', '50', '0', '52')\n",
            "('13', 'EVE', 'Everton', '37', '10', '15', '12', '41', '44', '-3', '45')\n",
            "('14', 'WOL', 'Wolverhampton Wanderers', '37', '12', '5', '20', '53', '68', '-15', '41')\n",
            "('15', 'WHU', 'West Ham United', '37', '10', '10', '17', '43', '61', '-18', '40')\n",
            "('16', 'MUN', 'Manchester United', '37', '10', '9', '18', '42', '54', '-12', '39')\n",
            "('17', 'TOT', 'Tottenham Hotspur', '37', '11', '5', '21', '63', '61', '+2', '38')\n",
            "('18', 'LEI', 'Leicester City', '37', '6', '7', '24', '33', '78', '-45', '25')\n",
            "('19', 'IPS', 'Ipswich Town', '37', '4', '10', '23', '35', '79', '-44', '22')\n",
            "('20', 'SOU', 'Southampton', '37', '2', '6', '29', '25', '84', '-59', '12')\n"
          ]
        }
      ]
    }
  ]
}
